const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 4795;
const DATA_FILE = path.join(__dirname, 'data.json');
const MAX_BODY_BYTES = 200 * 1024; // 200KB is generous for a chat-title list

// profileId must be a v4 UUID, generated by crypto.randomUUID() in the
// extension. Rejecting anything else blocks both HTML-injection and
// prototype-pollution attempts via keys like "__proto__" or "constructor".
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ALLOWED_PLATFORMS = new Set(['claude', 'chatgpt', 'gemini', 'grok']);

function loadData() {
  try {
    return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  } catch {
    return {};
  }
}

function saveData(data) {
  fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2));
}

function readBody(req, callback) {
  let body = '';
  let tooLarge = false;
  req.on('data', (chunk) => {
    body += chunk;
    if (body.length > MAX_BODY_BYTES) {
      tooLarge = true;
      req.destroy();
    }
  });
  req.on('end', () => {
    if (tooLarge) return; // connection was destroyed, no response needed
    callback(body);
  });
}

function sanitizeChats(rawChats) {
  if (!Array.isArray(rawChats)) return [];
  return rawChats
    .filter((c) => c && typeof c.id === 'string' && typeof c.title === 'string')
    .slice(0, 500) // cap list length
    .map((c) => ({
      id: c.id.slice(0, 300),
      title: c.title.slice(0, 300)
    }));
}

const server = http.createServer((req, res) => {
  if (req.method === 'GET' && req.url === '/') {
    const html = fs.readFileSync(path.join(__dirname, 'dashboard.html'), 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/html' });
    return res.end(html);
  }

  if (req.method === 'GET' && req.url === '/api/data') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify(loadData()));
  }

  if (req.method === 'POST' && req.url === '/update') {
    readBody(req, (body) => {
      try {
        const { profileId, profileLabel, platform, chats } = JSON.parse(body);
        if (typeof profileId !== 'string' || !UUID_RE.test(profileId)) {
          throw new Error('invalid profileId');
        }
        if (!ALLOWED_PLATFORMS.has(platform)) {
          throw new Error('invalid platform');
        }

        const safeChats = sanitizeChats(chats);
        const safeLabel = typeof profileLabel === 'string' ? profileLabel.slice(0, 100) : '';

        const data = loadData();
        const isNewProfile = !data[profileId];
        if (isNewProfile) {
          data[profileId] = { label: safeLabel, platforms: {} };
        }
        // Note: we deliberately do NOT update the label here on subsequent
        // calls. Labels are only ever changed via POST /label (triggered
        // from the popup or the dashboard), so a background scrape can
        // never silently revert a rename.

        const prev = data[profileId].platforms[platform]?.chats || [];
        const prevIds = new Set(prev.map((c) => c.id));
        const nextIds = new Set(safeChats.map((c) => c.id));

        const added = safeChats.filter((c) => !prevIds.has(c.id));
        const removed = prev.filter((c) => !nextIds.has(c.id));

        data[profileId].platforms[platform] = {
          chats: safeChats,
          lastUpdated: new Date().toISOString(),
          lastAdded: added.map((c) => c.title),
          lastRemoved: removed.map((c) => c.title)
        };

        saveData(data);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, added: added.length, removed: removed.length }));
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: err.message }));
      }
    });
    return;
  }

  if (req.method === 'POST' && req.url === '/label') {
    readBody(req, (body) => {
      try {
        const { profileId, label } = JSON.parse(body);
        if (typeof profileId !== 'string' || !UUID_RE.test(profileId)) {
          throw new Error('invalid profileId');
        }

        const safeLabel = typeof label === 'string' ? label.slice(0, 100) : '';

        const data = loadData();
        if (!data[profileId]) data[profileId] = { label: '', platforms: {} };
        data[profileId].label = safeLabel.trim();

        saveData(data);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: err.message }));
      }
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
});

// Bind explicitly to localhost only — without this, Node listens on all
// network interfaces by default, meaning anyone else on your WiFi/LAN
// could reach this server too.
server.listen(PORT, '127.0.0.1', () => {
  console.log(`AI Chat Tracker server running at http://localhost:${PORT}`);
});
